import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Typography from '@mui/material/Typography';
import { CardActionArea } from '@mui/material';
import { margin } from '@mui/system';

// TODO This will become the Join/Create Game page

export default function Home() {
  return (
    <>
      <h1>Welcome to Overthrown!</h1>
      <Card sx={{ maxWidth: 345, margin: 'auto' }}>
        <CardActionArea href='api/create'>
          <CardMedia
            component='img'
            height='140'
            image='/static/images/cards/contemplative-reptile.jpg'
            alt='green iguana'
          />
          <CardContent>
            <Typography gutterBottom variant='h5' component='div'>
              New Game
            </Typography>
            <Typography variant='body2' color='text.secondary'>
              Click here to start a new game of Overthrown!
            </Typography>
          </CardContent>
        </CardActionArea>
      </Card>
    </>
  );
  // (
  //   <div className={styles.container}>
  //     <Head>
  //       <title>Overthrown</title>
  //       <meta name='description' content='Generated by create next app' />
  //       <link rel='icon' href='/favicon.ico' />
  //     </Head>

  //     <main className={styles.main}>
  //       <h1 className={styles.title}>Welcome to Overthrown!</h1>

  //       <div className={styles.grid}>
  //         <a href='api/create' className={styles.card}>
  //           <h2>New Game &rarr;</h2>
  //           <p>Create a new Overthrown Game.</p>
  //         </a>
  //       </div>
  //     </main>

  //     <footer className={styles.footer}>
  //       <a
  //         href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
  //         target='_blank'
  //         rel='noopener noreferrer'
  //       >
  //         Powered by{' '}
  //         <span className={styles.logo}>
  //           <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
  //         </span>
  //       </a>
  //     </footer>
  //   </div>
  // );
}
